### ISSUE TITLE
Update GCC?

### ISSUE THREAD

**Issue by Sergeeeek** [pspdev/psptoolchain#59]
It would be nice to update it to have C++11 support and such. I'm not familiar with GCC myself, so I don't know where to start. If someone could nudge me in the right direction that'd be great.

**Comment by artart78** [comment]
I tried updating it, but it is very hard since some things —in binutils if I remember correctly— changed a lot, and we only apply a handmade patch, so I think some of it would have to be rewritten completely, and you would need to learn about the structure of binutils a lot. However, maybe you can update the gcc patch without touching the binutils one (you should check what is the dependency for gcc).

For the rest, you just have to look at binutils-2.22-PSP.patch and gcc-4.6.4-PSP.patch files in the patches/ directory, and try to apply them on the latest gcc, fixing things when it cannot be applied automatically. But note it can get very hard easily, mostly since we do not know the binutils structure enough.

**Comment by Sergeeeek** [comment]
Thanks, I'll try.

**Comment by Sergeeeek** [comment]
Never mind, apparently GCC 4.6.4 supports many C++11 features but they're disabled by default. Might be enough for me. :smile:
