### ISSUE TITLE
Failed installing: opentri

### ISSUE THREAD

**Issue by nicholas-c-jackson** [pspdev/psptoolchain#72]
A little side story first. It's been a while since I've developed for the PSP. Found my old unit with some old applications I wrote and felt like getting back into the scene. It's a little quieter than I was last here.

Regardless the installation of the openTRI game engine fails to compile during the psplibraries script. My platform is Ubuntu 14.04.1 4.2.0-34-generic. 

This is most likely an issue for the openTRI repository but that repository looks dormant. 

> triTexman.c: In function ‘triNearestColorIndex’:
> triTexman.c:820:1: error: unrecognizable insn:
>  }
>  ^
> (insn 237 236 238 37 (set (reg:SI 477)
>         (if_then_else:SI (ne:CC (reg:CC 67 $fcc0)
>                 (const_int 0 [0]))
>             (reg/v:SI 281 [ minIndex ])
>             (reg/v:SI 265 [ minIndex ]))) -1
>      (nil))
> triTexman.c:820:1: internal compiler error: in extract_insn, at recog.c:2202
> 0x7e242a _fatal_insn(char const_, rtx_def const_, char const_, int, char const_)
>     ../../gcc/rtl-error.c:109
> 0x7e2459 _fatal_insn_not_found(rtx_def const_, char const_, int, char const_)
>     ../../gcc/rtl-error.c:117
> 0x7b1d7a extract_insn(rtx_def_)
>     ../../gcc/recog.c:2202
> 0x687c2b instantiate_virtual_regs_in_insn
>     ../../gcc/function.c:1559
> 0x687c2b instantiate_virtual_regs
>     ../../gcc/function.c:1925
> 0x687c2b execute
>     ../../gcc/function.c:1975

I've never seen an internal compiler before. Any direction would be helpful.

Nicholas

**Comment by bazzinotti** [comment]
I'm having this same problem today!

**Comment by iaDRM** [comment]
The OpenTri bug looks to be something to do with this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58158

Bug reproducer from the above link (tweaked to use floats):

cat reproducer.c
```
extern void foo(void);

static inline float max(const float x, const float y)
{
        return (x > y) ? x : y;
}

void bar(int d)
{
        int i;

        for (i = 0; i < (int)max(100.f * d, 1.f); i++) {
                foo();
        }
}
```

Trying to compile the above with the current psp-gcc fails with the following error when using -O2 and above:

$ /usr/local/pspdev/bin/psp-gcc -O2 -c -o reproducer.o reproducer.c
```
reproducer.c: In function ‘bar’:
reproducer.c:15:1: error: unrecognizable insn:
 }
 ^
(insn 19 18 20 2 (set (reg:SI 202 [ D.1448 ])
        (if_then_else:SI (ne:CC (reg:CC 67 $fcc0)
                (const_int 0 [0]))
            (reg:SI 202 [ D.1448 ])
            (reg:SI 204))) -1
     (nil))
reproducer.c:15:1: internal compiler error: in extract_insn, at recog.c:2202

reproducer.c:15:1: internal compiler error: Abort trap: 6
psp-gcc: internal compiler error: Abort trap: 6 (program cc1)
Abort trap: 6
```

I've backported the fix for the failing instruction from the latest GCC, and tested the fixed psp-gcc against reproducer.c and the compile goes through, but I have not attempted running the binary that's produced nor have I spent time reading the disassembly. I will do that probably next week after I brush up on my MIPS.

If you're in a rush / want to confirm it for yourself, see the backported fix here:

https://github.com/iaDRM/psptoolchain/compare/xissue_72

After testing it, I will submit the pull request.

The disassembly of the reproducer.o:

```
00000000 <bar>:
   0:	44840800 	mtc1	a0,$f1
   4:	27bdfff0 	addiu	sp,sp,-16
   8:	46800820 	cvt.s.w	$f0,$f1
   c:	c7810000 	lwc1	$f1,0(gp)
  10:	afbf000c 	sw	ra,12(sp)
  14:	afb10008 	sw	s1,8(sp)
  18:	46010002 	mul.s	$f0,$f0,$f1
  1c:	c7810004 	lwc1	$f1,4(gp)
  20:	4600083c 	c.lt.s	$f1,$f0
  24:	00000000 	nop
  28:	4500000e 	bc1f	64 <bar+0x64>
  2c:	afb00004 	sw	s0,4(sp)
  30:	4600000d 	trunc.w.s	$f0,$f0
  34:	44110000 	mfc1	s1,$f0
  38:	08000012 	j	48 <bar+0x48>
  3c:	00008021 	move	s0,zero
  40:	0c000000 	jal	0 <bar>
  44:	26100001 	addiu	s0,s0,1
  48:	0211102a 	slt	v0,s0,s1
  4c:	1440fffc 	bnez	v0,40 <bar+0x40>
  50:	8fbf000c 	lw	ra,12(sp)
  54:	8fb10008 	lw	s1,8(sp)
  58:	8fb00004 	lw	s0,4(sp)
  5c:	03e00008 	jr	ra
  60:	27bd0010 	addiu	sp,sp,16
  64:	0800000e 	j	38 <bar+0x38>
  68:	24110001 	li	s1,1
```

**Comment by bazzinotti** [comment]
Sounds good, thanks!

**Comment by belldandu** [comment]
@iaDRM any news on this patch

**Comment by belldandu** [comment]
@iaDRM i just tested your fix and opentri does install properly now. However the sdk still appears broken see #78

**Comment by belldandu** [comment]
![screenshot_20170409-173047](https://cloud.githubusercontent.com/assets/5639384/24841130/54d3b2fc-1d4a-11e7-831b-2fdec8cdb499.png)

**Comment by Code0x58** [comment]
The `-mno-crt0` issue is because [build_prx.mak](https://github.com/pspdev/pspsdk/blob/master/src/base/build_prx.mak#L32) from the SDK expects that flag to be around (procfw expects it a lot too), but for some reason in the past ~6 years it has disappeared from the psp-gcc. I haven't looked into it more, but things compile when you remove the flag from that file, so there may or may not be a problem…

**Comment by carstene1ns** [comment]
This one should be retested with the new GCC.
