### ISSUE TITLE
Adding Travis-CI to test the toolchain

### ISSUE THREAD

**Issue by davidgfnet** [pspdev/psptoolchain#89]
This will probably involve adding some tests like, at least, building pspsdk samples or something like that. It would be a good idea to have such thing so we can be more confident about pull requests. I know it's impossible or very hard to do proper testing but hey...
If someone gets creative we might even be able to use some emulator!

**Comment by carstene1ns** [comment]
Get some active developers first… 🤕
The last active team members usually show up once or twice a year.

Do not get me wrong, I approve this as it is a good idea!

**Comment by davidgfnet** [comment]
Yup! I see that ScummVM is still using this, I guess some other open source projects still release new versions for PSP, since there's some projects out there that support really old hardware still.

**Comment by carstene1ns** [comment]
I am currently in the process of splitting the toolchain repo into a more logical role (only providing the bare toolchain) and have used github actions instead of good old travis-ci.
The pspdev repo takes the master role and provides a docker container and "ready-to-use" toolchains: https://github.com/pspdev/pspdev
The individual repos only provide their part as a docker layer that gets absorbed in the master image.
See https://github.com/pspdev/pspdev-docker/issues/12 for an overview.
